### PR TITLE
Test

### PR DESCRIPTION
**Pull request by tigamadou**
- Test cases added for all components
- Eslint errors fixed

### CODE REVIEW

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hello Team 👋

**You've both done really well on this.**

- [x] Simply include in your readme instructions to run tests and we are good to go.

Kindly fix this issue and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by tigamadou** [comment]
@mikenath223 Thank you very much. 👍

**Review by Dandush03 — APPROVED** [review]
# Status: :rocket: Approved :exclamation: 
## Great Work, Keep it up! :muscle: 
# Happy Coding :exclamation:

**Comment by tigamadou** [comment]
@Dandush03 Yes. Thank you. 🚀

**Pull request merged**
